-- Generated NPC list for NPCMarkers (do not edit by hand; use HideIds / ExtraNPCs in config.lua).
-- Source: every character definition with a unique name in the shipped AngelScript cache (GORE decompile),
-- English display names from the game localization (gore loc export), roles from the in-game glossary
-- (segments _Teach/_Train = teacher, _Trader/_Dealer/_Armor = trader). Generic role names are excluded.
return {
    { id = "UL_ORG_Aidan_859", name = "Aidan", kind = "teacher", orc = false, area = "Outside", label = "Assets/Labels/UL_ORG_Aidan_859.png", fallback = { 142709, -98908, -3946 } },
    { id = "SC_GUR_BaalCadar_1208", name = "Baal Cadar", kind = "both", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_BaalCadar_1208.png" },
    { id = "NC_ORG_Buster_833", name = "Buster", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Buster_833.png" },
    { id = "UL_STT_Cavalorn_336", name = "Cavalorn", kind = "both", orc = false, area = "Outside", label = "Assets/Labels/UL_STT_Cavalorn_336.png", fallback = { 128596, -97849, -5255 } },
    { id = "OW_OWR_Chokta_2407", name = "Chokta", kind = "teacher", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OWR_Chokta_2407.png" },
    { id = "SC_GUR_CorAngar_1202", name = "Cor Angar", kind = "teacher", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_CorAngar_1202.png" },
    { id = "NC_SLD_Cord_709", name = "Cord", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Cord_709.png" },
    { id = "OC_KDF_Corristo_402", name = "Corristo", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Corristo_402.png" },
    { id = "NC_KDW_Cronos_604", name = "Cronos", kind = "both", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Cronos_604.png" },
    { id = "OC_KDF_Damarok_401", name = "Damarok", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Damarok_401.png" },
    { id = "SC_NOV_Darrion_1312", name = "Darrion", kind = "both", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Darrion_1312.png" },
    { id = "OC_STT_Diego", name = "Diego", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Diego.png", fallback = { 114880, -98793, -4623 } },
    { id = "NC_ORG_Drax_819", name = "Drax", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Drax_819.png", fallback = { 118758, -83305, -4932 } },
    { id = "OC_STT_Fingers_331", name = "Fingers", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Fingers_331.png" },
    { id = "SC_TPL_GorNaToth_1402", name = "Gor Na Toth", kind = "both", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_TPL_GorNaToth_1402.png" },
    { id = "NC_BAU_Homer_935", name = "Homer", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Homer_935.png", fallback = { 169159, -89186, 60 } },
    { id = "NC_BAU_Horatio_901", name = "Horatio", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Horatio_901.png" },
    { id = "OC_VLK_Huno_538", name = "Huno", kind = "both", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Huno_538.png" },
    { id = "NC_BAU_Jan_942", name = "Jan", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Jan_942.png", fallback = { 153174, -102249, -3911 } },
    { id = "NC_ORG_Lares_801", name = "Lares", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Lares_801.png" },
    { id = "NC_SLD_Lee_700", name = "Lee", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Lee_700.png" },
    { id = "NC_KDW_Merdarion_602", name = "Merdarion", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Merdarion_602.png" },
    { id = "NC_KDW_Riordian_605", name = "Riordian", kind = "both", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Riordian_605.png" },
    { id = "NC_KDW_Saturas_600", name = "Saturas", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Saturas_600.png" },
    { id = "OCR_GRD_Scatty_210", name = "Scatty", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Scatty_210.png" },
    { id = "OC_GRD_Scorpio_205", name = "Scorpio", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Scorpio_205.png", fallback = { 116098, -102136, -4178 } },
    { id = "OCR_GRD_Stone_219", name = "Stone", kind = "both", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Stone_219.png" },
    { id = "SC_NOV_Theron_1372N", name = "Theron", kind = "teacher", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Theron_1372N.png", fallback = { 43537, -104149, -7748 } },
    { id = "OC_GRD_Thorus_200", name = "Thorus", kind = "teacher", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Thorus_200.png" },
    { id = "OC_KDF_Torrez_405", name = "Torrez", kind = "both", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Torrez_405.png" },
    { id = "UL_OSL_UrShak_2200", name = "Ur-Shak", kind = "teacher", orc = true, area = "Outside", label = "Assets/Labels/UL_OSL_UrShak_2200.png", fallback = { 104459, -127719, 5511 } },
    { id = "NC_ORG_Wedge_850", name = "Wedge", kind = "teacher", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Wedge_850.png" },
    { id = "NC_ORG_Wolf_855", name = "Wolf", kind = "both", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Wolf_855.png" },
    { id = "XT_DMB_Xardas_404", name = "Xardas", kind = "both", orc = false, area = "Xardas' Tower", label = "Assets/Labels/XT_DMB_Xardas_404.png", fallback = { 126047, -143287, 1761 } },
    { id = "OM_STT_Alberto_300", name = "Alberto", kind = "trader", orc = false, area = "Old Mine", label = "Assets/Labels/OM_STT_Alberto_300.png", fallback = { 132796, -59994, -8302 } },
    { id = "NC_NOV_BaalIsidro_1333", name = "Baal Isidro", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_NOV_BaalIsidro_1333.png" },
    { id = "NC_NOV_BaalKagan_1332", name = "Baal Kagan", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_NOV_BaalKagan_1332.png" },
    { id = "SC_GUR_BaalNamib_1204", name = "Baal Namib", kind = "trader", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_BaalNamib_1204.png" },
    { id = "NC_ORG_Cipher_873", name = "Cipher", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Cipher_873.png" },
    { id = "OC_STT_Dexter_329", name = "Dexter", kind = "trader", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Dexter_329.png" },
    { id = "OC_STT_Fisk_311", name = "Fisk", kind = "trader", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Fisk_311.png" },
    { id = "SC_NOV_Fortuno_1357", name = "Fortuno", kind = "trader", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Fortuno_1357.png" },
    { id = "OM_VLK_Glen_583", name = "Glen", kind = "trader", orc = false, area = "Old Mine", label = "Assets/Labels/OM_VLK_Glen_583.png" },
    { id = "NC_BAU_Jeremiah_912", name = "Jeremiah", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Jeremiah_912.png" },
    { id = "NC_BAU_Malon_930", name = "Malon", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Malon_930.png" },
    { id = "OC_ORG_Mordrag_826", name = "Mordrag", kind = "trader", orc = false, area = "Old Camp", label = "Assets/Labels/OC_ORG_Mordrag_826.png" },
    { id = "NC_ORG_Sharky_843", name = "Sharky", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Sharky_843.png" },
    { id = "NC_ORG_Silas_841", name = "Silas", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Silas_841.png" },
    { id = "OCR_GRD_Skip_211", name = "Skip", kind = "trader", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Skip_211.png" },
    { id = "BC_BAN_Torik_864", name = "Torik", kind = "trader", orc = false, area = "Bandit Camp", label = "Assets/Labels/BC_BAN_Torik_864.png" },
    { id = "NC_SLD_Torlof_737", name = "Torlof", kind = "trader", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Torlof_737.png" },
    { id = "OM_STT_Viper_302", name = "Viper", kind = "trader", orc = false, area = "Old Mine", label = "Assets/Labels/OM_STT_Viper_302.png", fallback = { 133274, -61037, -12365 } },
    { id = "OM_GRD_Aaron_262", name = "Aaron", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_GRD_Aaron_262.png" },
    { id = "OM_VLK_Aleph_585", name = "Aleph", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_VLK_Aleph_585.png" },
    { id = "BC_BAN_Arlin_852", name = "Arlin", kind = "other", orc = false, area = "Bandit Camp", label = "Assets/Labels/BC_BAN_Arlin_852.png" },
    { id = "OC_EBR_Arto_102", name = "Arto", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_EBR_Arto_102.png" },
    { id = "OM_GRD_Asghan_263", name = "Asghan", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_GRD_Asghan_263.png" },
    { id = "OG_GUR_BaalLukor_1211", name = "Baal Lukor", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OG_GUR_BaalLukor_1211.png" },
    { id = "SC_NOV_BaalNetbek_1371", name = "Baal Netbek", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_BaalNetbek_1371.png" },
    { id = "SC_GUR_BaalOrun_1209", name = "Baal Orun", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_BaalOrun_1209.png" },
    { id = "OC_NOV_BaalParvez_1330", name = "Baal Parvez", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_NOV_BaalParvez_1330.png" },
    { id = "OC_NOV_BaalTaran_1331", name = "Baal Taran", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_NOV_BaalTaran_1331.png" },
    { id = "SC_GUR_BaalTondral_1203", name = "Baal Tondral", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_BaalTondral_1203.png" },
    { id = "SC_GUR_BaalTyon_1210", name = "Baal Tyon", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_BaalTyon_1210.png" },
    { id = "OC_STT_Balam_324", name = "Balam", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Balam_324.png" },
    { id = "SC_NOV_Balor_1304", name = "Balor", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Balor_1304.png" },
    { id = "FM_SLD_Baloro_753", name = "Baloro", kind = "other", orc = false, area = "Free Mine", label = "Assets/Labels/FM_SLD_Baloro_753.png" },
    { id = "OC_EBR_Bartholo_106", name = "Bartholo", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_EBR_Bartholo_106.png" },
    { id = "NC_SLD_Blade_704", name = "Blade", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Blade_704.png" },
    { id = "OCR_GRD_Bloodwyn_233", name = "Bloodwyn", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Bloodwyn_233.png" },
    { id = "OM_GRD_Brandick_261", name = "Brandick", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_GRD_Brandick_261.png" },
    { id = "BC_BAN_Brannok_863", name = "Brannok", kind = "other", orc = false, area = "Bandit Camp", label = "Assets/Labels/BC_BAN_Brannok_863.png" },
    { id = "NC_ORG_Bruce_828", name = "Bruce", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Bruce_828.png" },
    { id = "OCR_GRD_Bullit_203", name = "Bullit", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Bullit_203.png" },
    { id = "NC_ORG_Butch_851", name = "Butch", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Butch_851.png" },
    { id = "SC_NOV_Caine_1301", name = "Caine", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Caine_1301.png" },
    { id = "SC_WSC_Chani_1205", name = "Chani", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_WSC_Chani_1205.png" },
    { id = "OC_IE_Charlotte", name = "Charlotte", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Charlotte.png" },
    { id = "UL_STT_Cohsel_337", name = "Cohsel", kind = "other", orc = false, area = "Outside", label = "Assets/Labels/UL_STT_Cohsel_337.png" },
    { id = "SC_GUR_CorKalom_1201", name = "Cor Kalom", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_CorKalom_1201.png" },
    { id = "OCR_GRD_Cutter_208", name = "Cutter", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OCR_GRD_Cutter_208.png" },
    { id = "OC_IE_Unicorn", name = "Das Letzte Einhorn", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Unicorn.png" },
    { id = "OC_IE_Lutter", name = "Die Lutte", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Lutter.png" },
    { id = "OC_IE_DrPymonte", name = "Dr. Pymonte", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_DrPymonte.png" },
    { id = "OC_KDF_Drago_403", name = "Drago", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Drago_403.png" },
    { id = "OM_GRD_Drake_260", name = "Drake", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_GRD_Drake_260.png" },
    { id = "OC_VLK_Dusty_524", name = "Dusty", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Dusty_524.png" },
    { id = "OC_GRD_Fletcher_255", name = "Fletcher", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Fletcher_255.png" },
    { id = "OC_IE_Flex", name = "Flex der Biegsame", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Flex.png" },
    { id = "OM_VLK_Garp_587", name = "Garp", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_VLK_Garp_587.png" },
    { id = "SC_NOV_Ghorim_1310", name = "Ghorim", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Ghorim_1310.png" },
    { id = "UL_NON_Gilbert_1500", name = "Gilbert", kind = "other", orc = false, area = "Outside", label = "Assets/Labels/UL_NON_Gilbert_1500.png" },
    { id = "OC_EBR_Gomez_100", name = "Gomez", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_EBR_Gomez_100.png" },
    { id = "ST_TPL_GorBoba_1455", name = "Gor Boba", kind = "other", orc = false, area = "Sleeper Temple", label = "Assets/Labels/ST_TPL_GorBoba_1455.png" },
    { id = "SC_TPL_GorHanis_1422", name = "Gor Hanis", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_TPL_GorHanis_1422.png" },
    { id = "OM_TPL_GorNaBar_1400", name = "Gor Na Bar", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_TPL_GorNaBar_1400.png" },
    { id = "SC_TPL_GorNaDrak_1439", name = "Gor Na Drak", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_TPL_GorNaDrak_1439.png" },
    { id = "SC_TPL_GorNaDun_1411", name = "Gor Na Dun", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_TPL_GorNaDun_1411.png" },
    { id = "OM_TPL_GorNaKosh_1401", name = "Gor Na Kosh", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_TPL_GorNaKosh_1401.png" },
    { id = "SC_TPL_GorNaRan_1405", name = "Gor Na Ran", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_TPL_GorNaRan_1405.png" },
    { id = "OM_TPL_GorNaVid_1433", name = "Gor Na Vid", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_TPL_GorNaVid_1433.png" },
    { id = "OG_TPL_GorNaZar_1446", name = "Gor Na Zar", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OG_TPL_GorNaZar_1446.png" },
    { id = "NC_SLD_GORN_699", name = "Gorn", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_GORN_699.png" },
    { id = "OC_VLK_Graham_573", name = "Graham", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Graham_573.png" },
    { id = "OC_VLK_Gravo_572", name = "Gravo", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Gravo_572.png" },
    { id = "OW_OWR_Grazkrak_2400", name = "Grazkrak", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OWR_Grazkrak_2400.png" },
    { id = "OC_VLK_Grim_580", name = "Grim", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Grim_580.png" },
    { id = "OM_VLK_Grimes_586", name = "Grimes", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_VLK_Grimes_586.png" },
    { id = "OC_VLK_Guy_530", name = "Guy", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Guy_530.png" },
    { id = "NC_SLD_Haenno_741", name = "Haenno", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Haenno_741.png" },
    { id = "SC_NOV_Harlok_1358", name = "Harlok", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Harlok_1358.png" },
    { id = "OC_VLK_Herek_511", name = "Herek", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Herek_511.png" },
    { id = "OM_STT_Ian_301", name = "Ian", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_STT_Ian_301.png" },
    { id = "OC_GRD_Jackal_201", name = "Jackal", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Jackal_201.png" },
    { id = "UL_ORG_Jacko_862", name = "Jacko", kind = "other", orc = false, area = "Outside", label = "Assets/Labels/UL_ORG_Jacko_862.png" },
    { id = "NC_SLD_Jarvis_728", name = "Jarvis", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Jarvis_728.png" },
    { id = "OC_VLK_Jesse_564", name = "Jesse", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Jesse_564.png" },
    { id = "SC_NOV_Joru_1305", name = "Joru", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Joru_1305.png" },
    { id = "OC_SLD_Kharim_729", name = "Kharim", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_SLD_Kharim_729.png" },
    { id = "UL_ORG_Killian_861", name = "Killian", kind = "other", orc = false, area = "Outside", label = "Assets/Labels/UL_ORG_Killian_861.png" },
    { id = "OC_GRD_Kirgo_251", name = "Kirgo", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Kirgo_251.png" },
    { id = "OW_OWR_Krashok_2405", name = "Krashok", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OWR_Krashok_2405.png" },
    { id = "OC_VLK_Kyle_536", name = "Kyle", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Kyle_536.png" },
    { id = "NC_ORG_Lefty_844", name = "Lefty", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Lefty_844.png" },
    { id = "SC_NOV_Lester", name = "Lester", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Lester.png" },
    { id = "SC_VLK_Melvin_582", name = "Melvin", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_VLK_Melvin_582.png" },
    { id = "OC_KDF_Milten", name = "Milten", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Milten.png" },
    { id = "OC_VLK_Mud_574", name = "Mud", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Mud_574.png" },
    { id = "OW_OPS_Muk_2404", name = "Muk", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OPS_Muk_2404.png" },
    { id = "NC_KDW_Myxir_601", name = "Myxir", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Myxir_601.png" },
    { id = "SC_WSC_Natalia_1207", name = "Natalia", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_WSC_Natalia_1207.png" },
    { id = "NC_KDW_Nefarius_603", name = "Nefarius", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_KDW_Nefarius_603.png" },
    { id = "OC_GRD_Nek_282", name = "Nek", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Nek_282.png" },
    { id = "SC_NOV_Nyras_1303", name = "Nyras", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Nyras_1303.png" },
    { id = "FM_SLD_Okyl_752", name = "Okyl", kind = "other", orc = false, area = "Free Mine", label = "Assets/Labels/FM_SLD_Okyl_752.png" },
    { id = "OC_STT_Omid_325", name = "Omid", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Omid_325.png" },
    { id = "FM_OSL_OrcSlave01_6001", name = "Orc Slave", kind = "other", orc = true, area = "Free Mine", label = "Assets/Labels/FM_OSL_OrcSlave01_6001.png" },
    { id = "NC_SLD_Orik_701", name = "Orik", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SLD_Orik_701.png" },
    { id = "OC_GRD_Orry_254", name = "Orry", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Orry_254.png" },
    { id = "OC_GRD_Pacho_224", name = "Pacho", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_GRD_Pacho_224.png" },
    { id = "NC_BAU_Pock_902", name = "Pock", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Pock_902.png" },
    { id = "BC_BAN_Quentin_858", name = "Quentin", kind = "other", orc = false, area = "Bandit Camp", label = "Assets/Labels/BC_BAN_Quentin_858.png" },
    { id = "NC_ORG_Ratford_818", name = "Ratford", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Ratford_818.png" },
    { id = "OC_EBR_Raven_105", name = "Raven", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_EBR_Raven_105.png" },
    { id = "NC_BAU_Rayk_941", name = "Rayk", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Rayk_941.png" },
    { id = "UL_ORG_Renyu_860", name = "Renyu", kind = "other", orc = false, area = "Outside", label = "Assets/Labels/UL_ORG_Renyu_860.png" },
    { id = "NC_BAU_RiceLord_900", name = "Rice Lord", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_RiceLord_900.png" },
    { id = "OC_KDF_Rodriguez_400", name = "Rodriguez", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_KDF_Rodriguez_400.png" },
    { id = "NC_ORG_Roscoe_840", name = "Roscoe", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Roscoe_840.png" },
    { id = "NC_BAU_Rufus_903", name = "Rufus", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_BAU_Rufus_903.png" },
    { id = "OM_STT_Santino_335", name = "Santino", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_STT_Santino_335.png" },
    { id = "OC_EBR_Scar_101", name = "Scar", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_EBR_Scar_101.png" },
    { id = "NC_SFB_Senyan_1000", name = "Senyan", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_SFB_Senyan_1000.png" },
    { id = "OC_WOC_Seraphia_110", name = "Seraphia", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_WOC_Seraphia_110.png" },
    { id = "SC_NOV_Shrat_1356", name = "Shrat", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Shrat_1356.png" },
    { id = "NC_ORG_Shrike_842", name = "Shrike", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Shrike_842.png" },
    { id = "OC_STT_Sly_315", name = "Sly", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Sly_315.png" },
    { id = "OC_VLK_Snaf_581", name = "Snaf", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_VLK_Snaf_581.png" },
    { id = "OM_VLK_Snipes_584", name = "Snipes", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_VLK_Snipes_584.png" },
    { id = "OC_IE_Specki_1401", name = "Specki T.D.", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Specki_1401.png" },
    { id = "OC_IE_Steve", name = "Steve", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_Steve.png" },
    { id = "FM_SFB_Swiney_1037", name = "Swiney", kind = "other", orc = false, area = "Free Mine", label = "Assets/Labels/FM_SFB_Swiney_1037.png" },
    { id = "OC_WOC_Syra_109", name = "Syra", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_WOC_Syra_109.png" },
    { id = "SC_NOV_Talas_1300", name = "Talas", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Talas_1300.png" },
    { id = "FM_OSL_Tarrok_2001", name = "Tarrok", kind = "other", orc = true, area = "Free Mine", label = "Assets/Labels/FM_OSL_Tarrok_2001.png" },
    { id = "OW_OWR_ToChurnagg_2403", name = "To-Churnagg", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OWR_ToChurnagg_2403.png" },
    { id = "OM_GRD_Ulbert_271", name = "Ulbert", kind = "other", orc = false, area = "Old Mine", label = "Assets/Labels/OM_GRD_Ulbert_271.png" },
    { id = "NC_ORG_Ulmar_881N", name = "Ulmar", kind = "other", orc = false, area = "New Camp", label = "Assets/Labels/NC_ORG_Ulmar_881N.png" },
    { id = "OW_OPS_Umakhal_2402", name = "Umakhal", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OPS_Umakhal_2402.png" },
    { id = "OW_OWR_Umosh_2406", name = "Umosh", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OWR_Umosh_2406.png" },
    { id = "OW_OSM_UrNazkrog_2401", name = "Ur-Nazkrog", kind = "other", orc = true, area = "Orc Territory", label = "Assets/Labels/OW_OSM_UrNazkrog_2401.png" },
    { id = "OC_IE_VanLange_1400", name = "Van Lange", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_IE_VanLange_1400.png" },
    { id = "ST_UOS_VarragArushat", name = "Varrag Arushat", kind = "other", orc = true, area = "Sleeper Temple", label = "Assets/Labels/ST_UOS_VarragArushat.png" },
    { id = "ST_UOS_VarragHashor", name = "Varrag Hashor", kind = "other", orc = true, area = "Sleeper Temple", label = "Assets/Labels/ST_UOS_VarragHashor.png" },
    { id = "ST_UOS_VarragKasorg", name = "Varrag Kasorg", kind = "other", orc = true, area = "Sleeper Temple", label = "Assets/Labels/ST_UOS_VarragKasorg.png" },
    { id = "ST_UOS_VarragRuuushk", name = "Varrag Ruuushk", kind = "other", orc = true, area = "Sleeper Temple", label = "Assets/Labels/ST_UOS_VarragRuuushk.png" },
    { id = "ST_UOS_VarragUnhilqt", name = "Varrag Unhilqt", kind = "other", orc = true, area = "Sleeper Temple", label = "Assets/Labels/ST_UOS_VarragUnhilqt.png" },
    { id = "OC_WOC_Velaya_108", name = "Velaya", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_WOC_Velaya_108.png" },
    { id = "SC_NOV_Viran_1302", name = "Viran", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_NOV_Viran_1302.png" },
    { id = "OC_STT_Whistler_309", name = "Whistler", kind = "other", orc = false, area = "Old Camp", label = "Assets/Labels/OC_STT_Whistler_309.png" },
    { id = "SC_GUR_YBerion_1200", name = "Y'Berion", kind = "other", orc = false, area = "Swamp Camp", label = "Assets/Labels/SC_GUR_YBerion_1200.png" },
}
