-- Generated from the GORE decompile of the game scripts (CL174209): the crime
-- rule table the game builds, and for each rule class where victims come from
-- (src: 0 area owner, 1 item owner, 2 object owner, 3 the named person) and who
-- writes the crime down (mode: 0 criminal, 1 witness, 2 victim, 3 story event).
return {
  vanilla = {
    { "Crime.Assault.Fists", "CrimeDefinition_Assault_Fists" },
    { "Crime.Assault.Weapon", "CrimeDefinition_Assault_Weapon" },
    { "Crime.DefeatedAgain", "CrimeDefinition_DefeatedAgain" },
    { "Crime.Defeated", "CrimeDefinition_Defeated" },
    { "Crime.Murder", "CrimeDefinition_Murder" },
    { "Crime.ThreateningWeaponDrawn", "CrimeDefinition_ThreateningWeaponDrawn" },
    { "Crime.FistsDrawn", "CrimeDefinition_FistsDrawn" },
    { "Crime.ThreateningWeaponTooClose", "CrimeDefinition_ThreateningWeaponTooClose" },
    { "Crime.FistsTooClose", "CrimeDefinition_FistsTooClose" },
    { "Crime.DirectThreat.Weapon", "CrimeDefinition_DirectThreat_Weapon" },
    { "Crime.DirectThreat.Fists", "CrimeDefinition_DirectThreat_Fists" },
    { "Crime.IgnoredWarning.WeaponDrawn", "CrimeDefinition_IgnoredWarning_WeaponDrawn" },
    { "Crime.IgnoredWarning.FistsDrawn", "CrimeDefinition_IgnoredWarning_FistsDrawn" },
    { "Crime.IgnoredWarning.DirectThreat.Weapon", "CrimeDefinition_IgnoredWarning_DirectThreat_Weapon" },
    { "Crime.IgnoredWarning.DirectThreat.Fists", "CrimeDefinition_IgnoredWarning_DirectThreat_Fists" },
    { "Crime.BlockingPath", "CrimeDefinition_BlockingPath" },
    { "Crime.Theft", "CrimeDefinition_Theft" },
    { "Crime.Lockpicking", "CrimeDefinition_Lockpicking" },
    { "Crime.IgnoredWarning.Lockpicking", "CrimeDefinition_IgnoredWarning_Lockpicking" },
    { "Crime.Interaction", "CrimeDefinition_Interaction" },
    { "Crime.IgnoredWarning.Interaction", "CrimeDefinition_IgnoredWarning_Interaction" },
    { "Crime.Pickpocket.Fail", "CrimeDefinition_Pickpocket_Fail" },
    { "Crime.Pickpocket.Success", "CrimeDefinition_Pickpocket_Success" },
    { "Crime.Dialogue.RealFight.Fists.Loot.Permanent", "CrimeDefinition_DialogueRealFight_Fists_Loot_Permanent" },
    { "Crime.Dialogue.RealFight.Fists.Loot.UntilDefeated", "CrimeDefinition_DialogueRealFight_Fists_Loot_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Fists.Loot.RegularDuration", "CrimeDefinition_DialogueRealFight_Fists_Loot_RegularDuration" },
    { "Crime.Dialogue.RealFight.Fists.Loot", "CrimeDefinition_DialogueRealFight_Fists_Loot_RegularDuration" },
    { "Crime.Dialogue.RealFight.Fists.NoPostActions.Permanent", "CrimeDefinition_DialogueRealFight_Fists_NoPostActions_Permanent" },
    { "Crime.Dialogue.RealFight.Fists.NoPostActions.UntilDefeated", "CrimeDefinition_DialogueRealFight_Fists_NoPostActions_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Fists.NoPostActions.RegularDuration", "CrimeDefinition_DialogueRealFight_Fists_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.RealFight.Fists.NoPostActions", "CrimeDefinition_DialogueRealFight_Fists_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.RealFight.Fists.ToDeath.Permanent", "CrimeDefinition_DialogueRealFight_Fists_ToDeath_Permanent" },
    { "Crime.Dialogue.RealFight.Fists.ToDeath.UntilDefeated", "CrimeDefinition_DialogueRealFight_Fists_ToDeath_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Fists.ToDeath.RegularDuration", "CrimeDefinition_DialogueRealFight_Fists_ToDeath_RegularDuration" },
    { "Crime.Dialogue.RealFight.Fists.ToDeath", "CrimeDefinition_DialogueRealFight_Fists_ToDeath_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.Loot.Permanent", "CrimeDefinition_DialogueRealFight_Weapon_Loot_Permanent" },
    { "Crime.Dialogue.RealFight.Weapon.Loot.UntilDefeated", "CrimeDefinition_DialogueRealFight_Weapon_Loot_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Weapon.Loot.RegularDuration", "CrimeDefinition_DialogueRealFight_Weapon_Loot_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.Loot", "CrimeDefinition_DialogueRealFight_Weapon_Loot_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.NoPostActions.Permanent", "CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_Permanent" },
    { "Crime.Dialogue.RealFight.Weapon.NoPostActions.UntilDefeated", "CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Weapon.NoPostActions.RegularDuration", "CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.NoPostActions", "CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.ToDeath.Permanent", "CrimeDefinition_DialogueRealFight_Weapon_ToDeath_Permanent" },
    { "Crime.Dialogue.RealFight.Weapon.ToDeath.UntilDefeated", "CrimeDefinition_DialogueRealFight_Weapon_ToDeath_UntilDefeated" },
    { "Crime.Dialogue.RealFight.Weapon.ToDeath.RegularDuration", "CrimeDefinition_DialogueRealFight_Weapon_ToDeath_RegularDuration" },
    { "Crime.Dialogue.RealFight.Weapon.ToDeath", "CrimeDefinition_DialogueRealFight_Weapon_ToDeath_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.Loot.Permanent", "CrimeDefinition_DialoguePettyFight_Fists_Loot_Permanent" },
    { "Crime.Dialogue.PettyFight.Fists.Loot.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Fists_Loot_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Fists.Loot.RegularDuration", "CrimeDefinition_DialoguePettyFight_Fists_Loot_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.Loot", "CrimeDefinition_DialoguePettyFight_Fists_Loot_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.NoPostActions.Permanent", "CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_Permanent" },
    { "Crime.Dialogue.PettyFight.Fists.NoPostActions.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Fists.NoPostActions.RegularDuration", "CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.NoPostActions", "CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.ToDeath.Permanent", "CrimeDefinition_DialoguePettyFight_Fists_ToDeath_Permanent" },
    { "Crime.Dialogue.PettyFight.Fists.ToDeath.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Fists_ToDeath_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Fists.ToDeath.RegularDuration", "CrimeDefinition_DialoguePettyFight_Fists_ToDeath_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Fists.ToDeath", "CrimeDefinition_DialoguePettyFight_Fists_ToDeath_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.Loot.Permanent", "CrimeDefinition_DialoguePettyFight_Weapon_Loot_Permanent" },
    { "Crime.Dialogue.PettyFight.Weapon.Loot.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Weapon_Loot_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Weapon.Loot.RegularDuration", "CrimeDefinition_DialoguePettyFight_Weapon_Loot_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.Loot", "CrimeDefinition_DialoguePettyFight_Weapon_Loot_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.NoPostActions.Permanent", "CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_Permanent" },
    { "Crime.Dialogue.PettyFight.Weapon.NoPostActions.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Weapon.NoPostActions.RegularDuration", "CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.NoPostActions", "CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.ToDeath.Permanent", "CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_Permanent" },
    { "Crime.Dialogue.PettyFight.Weapon.ToDeath.UntilDefeated", "CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_UntilDefeated" },
    { "Crime.Dialogue.PettyFight.Weapon.ToDeath.RegularDuration", "CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_RegularDuration" },
    { "Crime.Dialogue.PettyFight.Weapon.ToDeath", "CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_RegularDuration" },
    { "Crime.Trespassing.OnGuild", "CrimeDefinition_Crime_Trespassing" },
    { "Crime.Trespassing.OnPerson", "CrimeDefinition_Crime_Trespassing" },
    { "Crime.IgnoredWarning.Trespassing", "CrimeDefinition_IgnoredWarning_Trespassing" },
    { "Crime.Creeping", "CrimeDefinition_Creeping" },
    { "Crime.Anti.Defeated.Self", "CrimeDefinition_AntiCrime_Defeated_Self" },
    { "Crime.Anti.Defeated.Other", "CrimeDefinition_AntiCrime_Defeated_Other" },
  },
  defs = {
    CrimeDefinition_AntiCrime_Defeated_Other = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_AntiCrime_Defeated_Self = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_Assault_Fists = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_Assault_Weapon = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_BlockingPath = { src = 3, mode = 2, dur = 0, auto = false },
    CrimeDefinition_Creeping = { src = 3, mode = 2, dur = 0, auto = true },
    CrimeDefinition_Crime_Trespassing = { src = 0, mode = 0, dur = 0, auto = true },
    CrimeDefinition_Defeated = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_DefeatedAgain = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_Loot_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_Loot_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_Loot_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_NoPostActions_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_ToDeath_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_ToDeath_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Fists_ToDeath_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_Loot_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_Loot_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_Loot_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_NoPostActions_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialoguePettyFight_Weapon_ToDeath_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_Loot_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_Loot_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_Loot_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_NoPostActions_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_NoPostActions_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_NoPostActions_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_ToDeath_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_ToDeath_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Fists_ToDeath_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_Loot_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_Loot_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_Loot_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_NoPostActions_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_ToDeath_Permanent = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_ToDeath_RegularDuration = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DialogueRealFight_Weapon_ToDeath_UntilDefeated = { src = 3, mode = 3, dur = 1, auto = false },
    CrimeDefinition_DirectThreat_Fists = { src = 3, mode = 0, dur = 0, auto = false },
    CrimeDefinition_DirectThreat_Weapon = { src = 3, mode = 0, dur = 0, auto = false },
    CrimeDefinition_FistsDrawn = { src = 0, mode = 0, dur = 0, auto = false },
    CrimeDefinition_FistsTooClose = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_DirectThreat_Fists = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_DirectThreat_Weapon = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_FistsDrawn = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_Interaction = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_Lockpicking = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_Trespassing = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_IgnoredWarning_WeaponDrawn = { src = 3, mode = 2, dur = 1, auto = false },
    CrimeDefinition_Interaction = { src = 2, mode = 0, dur = 0, auto = true },
    CrimeDefinition_Lockpicking = { src = 2, mode = 0, dur = 0, auto = true },
    CrimeDefinition_Murder = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_Pickpocket_Fail = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_Pickpocket_Success = { src = 3, mode = 0, dur = 1, auto = false },
    CrimeDefinition_Theft = { src = 1, mode = 0, dur = 1, auto = false },
    CrimeDefinition_ThreateningWeaponDrawn = { src = 0, mode = 0, dur = 0, auto = false },
    CrimeDefinition_ThreateningWeaponTooClose = { src = 3, mode = 2, dur = 1, auto = false },
  },
}
