-- Settings of the module magic, described once: the default config.lua, the
-- groups on the page "Combat" of the settings app and of the in-game mod menu
-- are made from this.
-- (Plain values only - the settings app reads this file too. See dev/SETTINGS.md.)
local Schema = {}

Schema.Module = "magic"
Schema.Page = "Combat"
Schema.PageOrder = 10
Schema.Header = {
    "Magic balancing (module magic of G1R_MegaMod)",
    "Easiest way to change these: the settings app, page \"Combat\", or the",
    "in-game mod menu. Changes are picked up while the game is running.",
    "A multiplier of 1.0 leaves the game's own number alone; with every setting as",
    "shipped the module does not touch the game at all.",
}
-- what the text about the presets (PRESETS.txt) says below this module's values; the game does not read it
Schema.PresetNote = "The CircleCost numbers are learning points and count while CircleCosts is on (presets 3 to 5); 0 = a circle is learned for nothing."
Schema.Notes = {
    "Magic: the numbers of a spell are the game's own data. What is set here holds for everyone who casts with the hero's runes and scrolls, human mages included. Orc shamans, golems, demons and the companions of the last fight have spells of their own and stay as they are.",
    "Magic: a value is the game's number (or your own number, where there is one) times the multiplier for all spells, times the one for its kind, times the one for the spell. A changed value counts from the next cast on. Nothing is written into a save: with a setting back at 1.0, or the module switched off, the game's number is put back at once.",
    "Magic: use one magic balance mod at a time. While the mod G1R_MageBalance is enabled, this module is not loaded.",
}

Schema.Groups = {
    {
        Title = "Magic: all spells",
        Order = 30,
        Hint = "Multipliers: 1.0 leaves the game as it is. Those for a kind of spell and for single spells (the groups below) come on top.",
        Items = {
            { Key = "Enabled", Kind = "bool", Default = true,
              Tiers = "default",
              Label = "Magic balancing (this whole part of the mod)",
              Comment = "false = the module does nothing; every spell and every price is as the game has it.",
              MenuLabel = "Magic balancing", Menu = "off: every spell and price as the game has it" },
            { Key = "Damage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 10 },
              Label = "Damage of every spell", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of every damage spell. 1.0 = unchanged, 1.5 = half as much again, 0.5 = half.",
                          "It holds for everyone who casts with the hero's runes and scrolls, human mages included." } },
            { Key = "ManaCost", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 0.9, 0.75, 0.5, 0 },
              Label = "Mana cost of every spell", Unit = "times", Needs = "Enabled",
              Comment = "What a spell costs to cast, and what a held spell costs each second. 1.0 = unchanged, 0 = free.",
              Menu = "cost to cast and per second held; 0 = free" },
            { Key = "WholeMana", Kind = "bool", Default = true,
              Tiers = "default",
              Label = "Changed mana costs stay whole numbers", Needs = "Enabled",
              Comment = { "true = a changed mana cost is rounded to whole points. It never becomes 0 unless a multiplier is 0.",
                          "The game counts mana in whole points. false = the exact product is written (2 x 1.25 = 2.5);",
                          "what the game makes of half a point is not known." },
              MenuLabel = "Mana costs stay whole numbers" },
            { Key = "CastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 0.9, 0.8, 0.6, 0.1 },
              Label = "Casting and charging time of every spell", Unit = "times", Needs = "Enabled",
              Comment = "The time a spell takes to cast, or to charge to its next level. 1.0 = unchanged, 0.5 = twice as fast.",
              MenuLabel = "Cast and charge time (times)", Menu = "of every spell; 0.5 = twice as fast" },
            { Key = "ProjectileSpeed", Kind = "number", Default = 1.0, Min = 0.25, Max = 5, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1, 1.25, 1.5, 5 },
              Label = "Flight speed of bolts and balls", Unit = "times", Needs = "Enabled",
              Comment = "How fast fire bolt, ice bolt, fire ball, ball lightning and the storm of fire fly. 1.0 = unchanged.",
              MenuLabel = "Speed of bolts and balls (times)", Menu = "how fast bolts, balls and the storm of fire fly" },
            { Key = "Range", Kind = "number", Default = 1.0, Min = 0.25, Max = 4, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1, 1.25, 1.5, 4 },
              Label = "Reach of target spells and of three area spells", Unit = "times", Needs = "Enabled",
              Comment = { "How far a target spell finds its target and how far three area spells spread. 1.0 = unchanged.",
                          "Target spells: sleep, charm, shrink, heal, pyrokinesis, chain lightning, telekinesis, control.",
                          "Area spells: storm fist, death to the undead, Uriziel's wave of death. Other spells keep their reach." },
              MenuLabel = "Reach of target spells (times)", Menu = "and how far three area spells spread" },
            { Key = "Stagger", Kind = "number", Default = 1.0, Min = 0, Max = 20, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 20 },
              Label = "Force of spells against a foe's stance", Unit = "times", Needs = "Enabled",
              Comment = "How much of a foe's steadiness a spell hit takes away (what makes him stagger or fall). 1.0 = unchanged.",
              MenuLabel = "Force against stance (times)", Menu = "how much a hit makes a foe stagger or fall" },
            { Key = "HealAmount", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 10 },
              Label = "Health given by the heal spell", Unit = "times", Needs = "Enabled",
              Comment = { "The health a step of the heal spell gives back. 1.0 = unchanged.",
                          "The game has 4 to 30, by the caster's circle." },
              MenuLabel = "Health from the heal spell (times)" },
            { Key = "SchoolFire", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of fire spells", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the five fire spells, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "Fire bolt, fire ball, pyrokinesis, storm of fire, rain of fire." },
              Menu = "the five fire spells, on top of 'all spells'" },
            { Key = "SchoolIce", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of ice spells", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the three ice spells, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "Ice bolt, ice block, ice wave." },
              Menu = "the three ice spells, on top of 'all spells'" },
            { Key = "SchoolEnergy", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of energy spells", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the four energy spells, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "Ball lightning, chain lightning, Uriziel's wave of death, death to the undead." },
              Menu = "the four energy spells, on top of 'all spells'" },
            { Key = "SchoolWind", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of wind spells", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the three wind spells, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "Fist of wind, storm fist, breath of death." },
              Menu = "the three wind spells, on top of 'all spells'" },
        },
    },
    {
        Title = "Magic: fire spells",
        Order = 34,
        Items = {
            { Key = "FireBoltDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the fire bolt, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 35, up to 65 with the caster's circle." },
              Menu = "on top of 'all spells' and 'fire spells'" },
            { Key = "FireBoltMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the fire bolt, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 1 a shot." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "FireBoltCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the fire bolt, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.1 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "FireBallDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the fire ball, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 90 / 110 / 130 by charge." },
              Menu = "on top of 'all spells' and 'fire spells'" },
            { Key = "FireBallMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the fire ball, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 1 / 2 / 2 by charge." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "FireBallCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: charging time", Unit = "times", Needs = "Enabled",
              Comment = { "Charging time of the fire ball, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.4 / 0.6 / 0.8 s by charge." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "PyrokinesisDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of pyrokinesis, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 20, from the 5th circle 35." },
              Menu = "on top of 'all spells' and 'fire spells'" },
            { Key = "PyrokinesisMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of pyrokinesis, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 5, then 1 a second." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "PyrokinesisCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of pyrokinesis, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "StormOfFireDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the storm of fire, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 250, in the 6th circle 300." },
              Menu = "on top of 'all spells' and 'fire spells'" },
            { Key = "StormOfFireMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the storm of fire, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 30." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "StormOfFireCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the storm of fire, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "FireRainDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the rain of fire, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 50 a hit." },
              Menu = "on top of 'all spells' and 'fire spells'" },
            { Key = "FireRainMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the rain of fire, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 20." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "FireRainCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the rain of fire, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.1 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
        },
    },
    {
        Title = "Magic: ice spells",
        Order = 38,
        Items = {
            { Key = "IceBoltDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the ice bolt, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 20, up to 50 with the caster's circle." },
              Menu = "on top of 'all spells' and 'ice spells'" },
            { Key = "IceBoltMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the ice bolt, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 1 a shot." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "IceBoltCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the ice bolt, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.1 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "IceBoltFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, false, true },
              Label = "Ice bolt: freezes with every hit", Needs = "Enabled",
              Comment = { "true = every hit of the ice bolt freezes at once, also foes with ice resistance.",
                          "false = as the game has it: a hit freezes only when its damage fills the foe's ice counter (50 points)." },
              Menu = "every hit freezes, even foes resistant to ice" },
            { Key = "IceBlockDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the ice block, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 60, up to 100 with the caster's circle." },
              Menu = "on top of 'all spells' and 'ice spells'" },
            { Key = "IceBlockMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the ice block, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 3." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "IceBlockCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the ice block, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.2 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "IceBlockFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, true, true },
              Label = "Ice block: freezes with every hit", Needs = "Enabled",
              Comment = { "true = every hit of the ice block freezes at once, also foes with ice resistance.",
                          "false = as the game has it: a hit freezes only when its damage fills the foe's ice counter (50 points)." },
              Menu = "every hit freezes, even foes resistant to ice" },
            { Key = "IceWaveDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the ice wave, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 120, in the 6th circle 150." },
              Menu = "on top of 'all spells' and 'ice spells'" },
            { Key = "IceWaveMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the ice wave, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 15." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "IceWaveCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the ice wave, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.2 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "IceWaveFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, false, true },
              Label = "Ice wave: freezes with every hit", Needs = "Enabled",
              Comment = { "true = every hit of the ice wave freezes at once, also foes with ice resistance.",
                          "false = as the game has it: a hit freezes only when its damage fills the foe's ice counter (50 points)." },
              Menu = "every hit freezes, even foes resistant to ice" },
        },
    },
    {
        Title = "Magic: energy spells",
        Order = 42,
        Items = {
            { Key = "BallLightningDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the ball lightning, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 70 / 90 / 110 / 150 by charge." },
              Menu = "on top of 'all spells' and 'energy spells'" },
            { Key = "BallLightningMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the ball lightning, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 5 / 1 / 1 / 2 by charge." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "BallLightningCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: charging time", Unit = "times", Needs = "Enabled",
              Comment = { "Charging time of the ball lightning, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.3 s, then 1.03 s a charge." },
              MenuLabel = "Ball lightning: charge time (times)", Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "BallLightningSpeed", Kind = "number", Default = 0, Min = 0, Max = 5000, Step = 50, Decimals = 0,
              Tiers = "default",
              Label = "Ball lightning: flight speed", Unit = "units a second (0 = the game's)", Needs = "Enabled",
              Comment = { "The speed of the ball at every charge level. 0 = as the game has it (300 to 450, rising with the charge).",
                          "The multiplier for the flight speed of all spells comes on top." },
              MenuLabel = "Ball lightning: speed", Menu = "units a second at every charge; 0 = the game's" },
            { Key = "ChainLightningDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the chain lightning, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 20, up to 45 with the caster's circle." },
              Menu = "on top of 'all spells' and 'energy spells'" },
            { Key = "ChainLightningMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the chain lightning, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 5, then 1 a second." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "ChainLightningCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the chain lightning, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              MenuLabel = "Chain lightning: cast time (times)", Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "UrizielDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of Uriziel's wave of death, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 90." },
              MenuLabel = "Uriziel's wave: damage (times)", Menu = "on top of 'all spells' and 'energy spells'" },
            { Key = "UrizielMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of Uriziel's wave of death, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 40." },
              MenuLabel = "Uriziel's wave: mana cost (times)", Menu = "on top of 'all spells'; 0 = free" },
            { Key = "UrizielCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of Uriziel's wave of death, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.3 s." },
              MenuLabel = "Uriziel's wave: cast time (times)", Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "DeathToTheUndeadDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of death to the undead, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 500." },
              Menu = "on top of 'all spells' and 'energy spells'" },
            { Key = "DeathToTheUndeadMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of death to the undead, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 25." },
              MenuLabel = "Death to undead: mana cost (times)", Menu = "on top of 'all spells'; 0 = free" },
            { Key = "DeathToTheUndeadCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of death to the undead, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              MenuLabel = "Death to undead: cast time (times)", Menu = "on top of 'all spells'; 0.5 = twice as fast" },
        },
    },
    {
        Title = "Magic: wind spells",
        Order = 46,
        Items = {
            { Key = "WindFistDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the fist of wind, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 20, up to 70 with the caster's circle." },
              Menu = "on top of 'all spells' and 'wind spells'" },
            { Key = "WindFistMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the fist of wind, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 2." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "WindFistStagger", Kind = "number", Default = 1.0, Min = 0, Max = 20, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: force against a foe's stance", Unit = "times", Needs = "Enabled",
              Comment = { "How hard the fist of wind staggers, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 200; a storm fist has 250. Orcs and other heavy foes stand firm against too little." },
              MenuLabel = "Fist of wind: stance force (times)", Menu = "how hard it staggers, on top of 'all spells'" },
            { Key = "StormFistDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the storm fist, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 120, in the 6th circle 160." },
              Menu = "on top of 'all spells' and 'wind spells'" },
            { Key = "StormFistMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the storm fist, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 10." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "StormFistCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the storm fist, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              Menu = "on top of 'all spells'; 0.5 = twice as fast" },
            { Key = "BreathOfDeathDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: damage", Unit = "times", Needs = "Enabled",
              Comment = { "Damage of the breath of death, on top of the multipliers for all spells and its kind. 1.0 = unchanged.",
                          "The game has 150." },
              Menu = "on top of 'all spells' and 'wind spells'" },
            { Key = "BreathOfDeathMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: mana cost", Unit = "times", Needs = "Enabled",
              Comment = { "Mana cost of the breath of death, on top of the multiplier for all spells. 1.0 = unchanged, 0 = free.",
                          "The game has 15." },
              Menu = "on top of 'all spells'; 0 = free" },
            { Key = "BreathOfDeathCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: casting time", Unit = "times", Needs = "Enabled",
              Comment = { "Casting time of the breath of death, on top of the multiplier for all spells. 1.0 = unchanged.",
                          "The game has 0.5 s." },
              MenuLabel = "Breath of death: cast time (times)", Menu = "on top of 'all spells'; 0.5 = twice as fast" },
        },
    },
    {
        Title = "Magic: fire bolt and ice bolt by the caster's circle", MenuTitle = "Bolt damage by circle",
        Order = 50,
        Hint = "These two spells grow with the caster's magic circle. With a switch on, its four numbers replace the game's.",
        Items = {
            { Key = "FireBoltSteps", Kind = "bool", Default = false,
              Tiers = "default",
              Label = "Own damage numbers for the fire bolt", Needs = "Enabled",
              Comment = { "true = the four numbers below are the damage of the fire bolt. The multipliers still apply.",
                          "false = the game's own numbers (35 / 40 / 50 / 65)." },
              MenuLabel = "Own fire bolt damage", Menu = "on: the four numbers below are its damage" },
            { Key = "FireBoltStep0", Kind = "number", Default = 35, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt below the 2nd circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "Damage of the fire bolt of a caster below the 2nd circle (the game has 35).",
              MenuLabel = "Fire bolt, below 2nd circle", Menu = "damage before the 2nd circle (the game has 35)" },
            { Key = "FireBoltStep2", Kind = "number", Default = 40, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt from the 2nd circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "Damage of the fire bolt of a caster of the 2nd or 3rd circle (the game has 40).",
              MenuLabel = "Fire bolt, 2nd-3rd circle", Menu = "damage in the 2nd or 3rd circle (the game has 40)" },
            { Key = "FireBoltStep4", Kind = "number", Default = 50, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt from the 4th circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "Damage of the fire bolt of a caster of the 4th or 5th circle (the game has 50).",
              MenuLabel = "Fire bolt, 4th-5th circle", Menu = "damage in the 4th or 5th circle (the game has 50)" },
            { Key = "FireBoltStep6", Kind = "number", Default = 65, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt in the 6th circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "Damage of the fire bolt of a caster of the 6th circle (the game has 65).",
              MenuLabel = "Fire bolt, 6th circle", Menu = "damage in the 6th circle (the game has 65)" },
            { Key = "IceBoltSteps", Kind = "bool", Default = false,
              Tiers = "default",
              Label = "Own damage numbers for the ice bolt", Needs = "Enabled",
              Comment = { "true = the four numbers below are the damage of the ice bolt. The multipliers still apply.",
                          "false = the game's own numbers (20 / 30 / 40 / 50)." },
              MenuLabel = "Own ice bolt damage", Menu = "on: the four numbers below are its damage" },
            { Key = "IceBoltStep0", Kind = "number", Default = 20, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt below the 2nd circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "Damage of the ice bolt of a caster below the 2nd circle (the game has 20).",
              MenuLabel = "Ice bolt, below 2nd circle", Menu = "damage before the 2nd circle (the game has 20)" },
            { Key = "IceBoltStep2", Kind = "number", Default = 30, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt from the 2nd circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "Damage of the ice bolt of a caster of the 2nd or 3rd circle (the game has 30).",
              MenuLabel = "Ice bolt, 2nd-3rd circle", Menu = "damage in the 2nd or 3rd circle (the game has 30)" },
            { Key = "IceBoltStep4", Kind = "number", Default = 40, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt from the 4th circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "Damage of the ice bolt of a caster of the 4th or 5th circle (the game has 40).",
              MenuLabel = "Ice bolt, 4th-5th circle", Menu = "damage in the 4th or 5th circle (the game has 40)" },
            { Key = "IceBoltStep6", Kind = "number", Default = 50, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt in the 6th circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "Damage of the ice bolt of a caster of the 6th circle (the game has 50).",
              MenuLabel = "Ice bolt, 6th circle", Menu = "damage in the 6th circle (the game has 50)" },
        },
    },
    {
        Title = "Magic: learning the circles",
        Order = 54,
        Hint = "What a teacher takes for a magic circle, in learning points.",
        Items = {
            { Key = "CircleCosts", Kind = "bool", Default = false,
              Tiers = { false, false, true, true, true },
              Label = "Own prices for the magic circles", Needs = "Enabled",
              Comment = "true = the numbers below are what the magic circles cost. false = the game's own prices.",
              Menu = "on: the numbers below are what the circles cost" },
            { Key = "CircleCostBasics", Kind = "number", Default = 5, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 5, 5, 4, 3, 0 },
              Label = "The basics of magic (before the 1st circle)", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the basics of magic (the game has 5).",
              MenuLabel = "Basics of magic (learning points)", Menu = "before the 1st circle (the game has 5)" },
            { Key = "CircleCost1", Kind = "number", Default = 10, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 10, 10, 8, 5, 0 },
              Label = "The 1st circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 1st circle (the game has 10).",
              Menu = "what a teacher takes (the game has 10)" },
            { Key = "CircleCost2", Kind = "number", Default = 15, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 15, 15, 12, 8, 0 },
              Label = "The 2nd circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 2nd circle (the game has 15).",
              Menu = "what a teacher takes (the game has 15)" },
            { Key = "CircleCost3", Kind = "number", Default = 20, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 20, 20, 16, 10, 0 },
              Label = "The 3rd circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 3rd circle (the game has 20).",
              Menu = "what a teacher takes (the game has 20)" },
            { Key = "CircleCost4", Kind = "number", Default = 25, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 25, 25, 20, 13, 0 },
              Label = "The 4th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 4th circle (the game has 25).",
              Menu = "what a teacher takes (the game has 25)" },
            { Key = "CircleCost5", Kind = "number", Default = 30, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 30, 30, 24, 15, 0 },
              Label = "The 5th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 5th circle (the game has 30).",
              Menu = "what a teacher takes (the game has 30)" },
            { Key = "CircleCost6", Kind = "number", Default = 40, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 40, 40, 32, 20, 0 },
              Label = "The 6th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "Learning points a teacher takes for the 6th circle (the game has 40).",
              Menu = "what a teacher takes (the game has 40)" },
        },
    },
    {
        Title = "Magic: on screen, log",
        Order = 58,
        Items = {
            { Key = "ShowMessage", Kind = "bool", Default = true,
              Label = "Show a short note when changed settings have reached the game", Needs = "Enabled",
              Comment = { "A short note on screen when a change of these settings has been carried into the game.",
                          "How notes look is set on the page \"General\"." },
              MenuLabel = "Note when changes reached the game", Menu = "a short note when a change is in the game" },
            { Key = "LogChanges", Kind = "bool", Default = false,
              Label = "One line in UE4SS.log for every value that is changed or put back", Needs = "Enabled",
              Comment = "One line in UE4SS.log for every value that is changed or put back.",
              MenuLabel = "Log every value changed", Menu = "one line in UE4SS.log per value changed or put back" },
            { Key = "Status", Kind = "action", Label = "Write what is changed right now into UE4SS.log",
              Comment = "Writes the state of the module and every changed value into UE4SS.log.",
              MenuLabel = "Write the changes to the log", Menu = "the module's state and every changed value" },
        },
    },
    {
        Title = "Advanced",
        Order = 59,
        Items = {
            -- not shown in the app or the menu, not in the shipped file; can be added to config.lua by hand
            -- how many of the game's data objects are searched for per look (each search costs a few milliseconds, once per run)
            { Key = "SearchesPerLook", Kind = "number", Default = 4, Min = 1, Max = 32, Decimals = 0, Hidden = true },
            -- every so many seconds the changed values are looked at again (0 = only after a map change)
            { Key = "CheckSeconds", Kind = "number", Default = 60, Min = 0, Max = 3600, Decimals = 0, Hidden = true },
            -- how often the module looks whether there is something to do (read once, when the game starts)
            { Key = "LookMilliseconds", Kind = "number", Default = 250, Min = 50, Max = 5000, Decimals = 0, Hidden = true },
        },
    },
}

return Schema
