-- Settings of the module magic, described once: the default config.lua, the
-- groups on the page "Combat" of the settings app and of the in-game mod menu
-- are made from this.
-- (Plain values only - the settings app reads this file too. See dev/SETTINGS.md.)
local Schema = {}

Schema.Module = "magic"
Schema.Page = "Combat"
Schema.PageOrder = 10
Schema.Header = {
    "Magic balancing (module magic of G1R_MegaMod)",
    "Set in the settings app or the in-game mod menu; changes count while the game runs.",
    "1.0 = the game's number. As shipped the module changes nothing.",
}
-- what the text about the presets (PRESETS.txt) says below this module's values; the game does not read it
Schema.PresetNote = "The CircleCost numbers are learning points and count while CircleCosts is on (presets 3 to 5); 0 = a circle is learned for nothing."
Schema.Notes = {
    "Magic: counts for every caster of the hero's runes and scrolls, human mages too. Orc shamans, golems, demons and the last fight's companions keep their spells.",
    "Magic: a value = the game's number x all spells x its kind x the spell. Counts from the next cast. Nothing goes into a save: 1.0 or off puts the game's number back.",
    "Magic: not loaded while the mod G1R_MageBalance is enabled.",
}

Schema.Groups = {
    {
        Title = "Magic: all spells",
        Order = 30,
        Hint = "1.0 = unchanged. The multipliers for a kind and for single spells (below) come on top.",
        Items = {
            { Key = "Enabled", Kind = "bool", Default = true,
              Tiers = "default",
              Label = "Magic balancing",
              Comment = "Off: every spell and price as the game has it." },
            { Key = "Damage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 10 },
              Label = "Damage of every spell", Unit = "times", Needs = "Enabled",
              Comment = "1.5 = half as much again, 0.5 = half." },
            { Key = "ManaCost", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 0.9, 0.75, 0.5, 0 },
              Label = "Mana cost of every spell", Unit = "times", Needs = "Enabled",
              Comment = "To cast, and each second held. 0 = free." },
            { Key = "WholeMana", Kind = "bool", Default = true,
              Tiers = "default",
              Label = "Mana costs stay whole numbers", Needs = "Enabled",
              Comment = "Rounded, never 0 unless a multiplier is 0. Off: exact (2.5); the game's handling is unknown." },
            { Key = "CastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 0.9, 0.8, 0.6, 0.1 },
              Label = "Cast and charge time", Unit = "times", Needs = "Enabled",
              Comment = "0.5 = twice as fast." },
            { Key = "ProjectileSpeed", Kind = "number", Default = 1.0, Min = 0.25, Max = 5, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1, 1.25, 1.5, 5 },
              Label = "Speed of bolts and balls", Unit = "times", Needs = "Enabled",
              Comment = "Fire bolt, ice bolt, fire ball, ball lightning, storm of fire.",
              Menu = "bolts, fire ball, ball lightning, storm of fire" },
            { Key = "Range", Kind = "number", Default = 1.0, Min = 0.25, Max = 4, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1, 1.25, 1.5, 4 },
              Label = "Reach of target spells", Unit = "times", Needs = "Enabled",
              Comment = { "Sleep, charm, shrink, heal, pyrokinesis, chain lightning, telekinesis, control;",
                          "and the spread of storm fist, death to the undead, Uriziel's wave of death." },
              Menu = "and the spread of three area spells" },
            { Key = "Stagger", Kind = "number", Default = 1.0, Min = 0, Max = 20, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 20 },
              Label = "Force against stance", Unit = "times", Needs = "Enabled",
              Comment = "How much a hit makes a foe stagger or fall." },
            { Key = "HealAmount", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = { 1, 1.25, 1.5, 2.5, 10 },
              Label = "Health from the heal spell", Unit = "times", Needs = "Enabled",
              Comment = "The game: 4 to 30 a step, by circle." },
            { Key = "SchoolFire", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of fire spells", Unit = "times", Needs = "Enabled",
              Comment = "Fire bolt, fire ball, pyrokinesis, storm of fire, rain of fire.",
              Menu = "bolt, ball, pyrokinesis, storm and rain of fire" },
            { Key = "SchoolIce", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of ice spells", Unit = "times", Needs = "Enabled",
              Comment = "Ice bolt, ice block, ice wave." },
            { Key = "SchoolEnergy", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of energy spells", Unit = "times", Needs = "Enabled",
              Comment = "Ball lightning, chain lightning, Uriziel's wave of death, death to the undead.",
              Menu = "ball/chain lightning, Uriziel's wave, death to undead" },
            { Key = "SchoolWind", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Damage of wind spells", Unit = "times", Needs = "Enabled",
              Comment = "Fist of wind, storm fist, breath of death." },
        },
    },
    {
        Title = "Magic: fire spells",
        Order = 34,
        Hint = "On top of all spells and the kind. 1.0 = unchanged.",
        Items = {
            { Key = "FireBoltDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 35, up to 65 with the caster's circle." },
            { Key = "FireBoltMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 1 a shot. 0 = free." },
            { Key = "FireBoltCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire bolt: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.1 s." },
            { Key = "FireBallDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 90 / 110 / 130 by charge." },
            { Key = "FireBallMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 1 / 2 / 2 by charge. 0 = free." },
            { Key = "FireBallCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fire ball: charging time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.4 / 0.6 / 0.8 s by charge." },
            { Key = "PyrokinesisDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 20, from the 5th circle 35." },
            { Key = "PyrokinesisMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 5, then 1 a second. 0 = free." },
            { Key = "PyrokinesisCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Pyrokinesis: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s." },
            { Key = "StormOfFireDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 250, in the 6th circle 300." },
            { Key = "StormOfFireMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 30. 0 = free." },
            { Key = "StormOfFireCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm of fire: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s." },
            { Key = "FireRainDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 50 a hit." },
            { Key = "FireRainMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 20. 0 = free." },
            { Key = "FireRainCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Rain of fire: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.1 s." },
        },
    },
    {
        Title = "Magic: ice spells",
        Order = 38,
        Hint = "On top of all spells and the kind. 1.0 = unchanged.",
        Items = {
            { Key = "IceBoltDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 20, up to 50 with the caster's circle." },
            { Key = "IceBoltMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 1 a shot. 0 = free." },
            { Key = "IceBoltCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice bolt: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.1 s." },
            { Key = "IceBoltFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, false, true },
              Label = "Ice bolt: freezes with every hit", Needs = "Enabled",
              Comment = "Also foes resistant to ice. Off: only when the ice counter fills (50).",
              Menu = "every hit freezes, even foes resistant to ice" },
            { Key = "IceBlockDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 60, up to 100 with the caster's circle." },
            { Key = "IceBlockMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 3. 0 = free." },
            { Key = "IceBlockCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice block: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.2 s." },
            { Key = "IceBlockFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, true, true },
              Label = "Ice block: freezes with every hit", Needs = "Enabled",
              Comment = "Also foes resistant to ice. Off: only when the ice counter fills (50).",
              Menu = "every hit freezes, even foes resistant to ice" },
            { Key = "IceWaveDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 120, in the 6th circle 150." },
            { Key = "IceWaveMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 15. 0 = free." },
            { Key = "IceWaveCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ice wave: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.2 s." },
            { Key = "IceWaveFreeze", Kind = "bool", Default = false,
              Tiers = { false, false, false, false, true },
              Label = "Ice wave: freezes with every hit", Needs = "Enabled",
              Comment = "Also foes resistant to ice. Off: only when the ice counter fills (50).",
              Menu = "every hit freezes, even foes resistant to ice" },
        },
    },
    {
        Title = "Magic: energy spells",
        Order = 42,
        Hint = "On top of all spells and the kind. 1.0 = unchanged.",
        Items = {
            { Key = "BallLightningDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 70 / 90 / 110 / 150 by charge." },
            { Key = "BallLightningMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 5 / 1 / 1 / 2 by charge. 0 = free." },
            { Key = "BallLightningCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Ball lightning: charging time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.3 s, then 1.03 s a charge.",
              MenuLabel = "Ball lightning: charge time (times)" },
            { Key = "BallLightningSpeed", Kind = "number", Default = 0, Min = 0, Max = 5000, Step = 50, Decimals = 0,
              Tiers = "default",
              Label = "Ball lightning: flight speed", Unit = "units a second (0 = the game's)", Needs = "Enabled",
              Comment = "0 = the game's (300 to 450 by charge). The speed multiplier comes on top.",
              MenuLabel = "Ball lightning: speed", Menu = "units a second at every charge; 0 = the game's" },
            { Key = "ChainLightningDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 20, up to 45 with the caster's circle." },
            { Key = "ChainLightningMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 5, then 1 a second. 0 = free." },
            { Key = "ChainLightningCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Chain lightning: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s.",
              MenuLabel = "Chain lightning: cast time (times)" },
            { Key = "UrizielDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 90.",
              MenuLabel = "Uriziel's wave: damage (times)" },
            { Key = "UrizielMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 40. 0 = free.",
              MenuLabel = "Uriziel's wave: mana cost (times)" },
            { Key = "UrizielCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Uriziel's wave of death: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.3 s.",
              MenuLabel = "Uriziel's wave: cast time (times)" },
            { Key = "DeathToTheUndeadDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 500." },
            { Key = "DeathToTheUndeadMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 25. 0 = free.",
              MenuLabel = "Death to undead: mana cost (times)" },
            { Key = "DeathToTheUndeadCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Death to the undead: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s.",
              MenuLabel = "Death to undead: cast time (times)" },
        },
    },
    {
        Title = "Magic: wind spells",
        Order = 46,
        Hint = "On top of all spells and the kind. 1.0 = unchanged.",
        Items = {
            { Key = "WindFistDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 20, up to 70 with the caster's circle." },
            { Key = "WindFistMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 2. 0 = free." },
            { Key = "WindFistStagger", Kind = "number", Default = 1.0, Min = 0, Max = 20, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Fist of wind: force against a foe's stance", Unit = "times", Needs = "Enabled",
              Comment = "The game: 200 (storm fist 250). Heavy foes like orcs resist too little.",
              MenuLabel = "Fist of wind: stance force (times)" },
            { Key = "StormFistDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 120, in the 6th circle 160." },
            { Key = "StormFistMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 10. 0 = free." },
            { Key = "StormFistCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Storm fist: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s." },
            { Key = "BreathOfDeathDamage", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: damage", Unit = "times", Needs = "Enabled",
              Comment = "The game: 150." },
            { Key = "BreathOfDeathMana", Kind = "number", Default = 1.0, Min = 0, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: mana cost", Unit = "times", Needs = "Enabled",
              Comment = "The game: 15. 0 = free." },
            { Key = "BreathOfDeathCastTime", Kind = "number", Default = 1.0, Min = 0.1, Max = 10, Step = 0.05, Decimals = 3,
              Tiers = "default",
              Label = "Breath of death: casting time", Unit = "times", Needs = "Enabled",
              Comment = "The game: 0.5 s.",
              MenuLabel = "Breath of death: cast time (times)" },
        },
    },
    {
        Title = "Magic: fire bolt and ice bolt by the caster's circle", MenuTitle = "Bolt damage by circle",
        Order = 50,
        Hint = "With a switch on, its four numbers replace the game's. Multipliers still apply.",
        Items = {
            { Key = "FireBoltSteps", Kind = "bool", Default = false,
              Tiers = "default",
              Label = "Own damage numbers for the fire bolt", Needs = "Enabled",
              Comment = "The game: 35 / 40 / 50 / 65.",
              MenuLabel = "Own fire bolt damage", Menu = "on: the four numbers below are its damage" },
            { Key = "FireBoltStep0", Kind = "number", Default = 35, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt below the 2nd circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "The game: 35.",
              MenuLabel = "Fire bolt, below 2nd circle" },
            { Key = "FireBoltStep2", Kind = "number", Default = 40, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt from the 2nd circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "The game: 40.",
              MenuLabel = "Fire bolt, 2nd-3rd circle" },
            { Key = "FireBoltStep4", Kind = "number", Default = 50, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt from the 4th circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "The game: 50.",
              MenuLabel = "Fire bolt, 4th-5th circle" },
            { Key = "FireBoltStep6", Kind = "number", Default = 65, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Fire bolt in the 6th circle", Unit = "damage", Needs = "FireBoltSteps",
              Comment = "The game: 65.",
              MenuLabel = "Fire bolt, 6th circle" },
            { Key = "IceBoltSteps", Kind = "bool", Default = false,
              Tiers = "default",
              Label = "Own damage numbers for the ice bolt", Needs = "Enabled",
              Comment = "The game: 20 / 30 / 40 / 50.",
              MenuLabel = "Own ice bolt damage", Menu = "on: the four numbers below are its damage" },
            { Key = "IceBoltStep0", Kind = "number", Default = 20, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt below the 2nd circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "The game: 20.",
              MenuLabel = "Ice bolt, below 2nd circle" },
            { Key = "IceBoltStep2", Kind = "number", Default = 30, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt from the 2nd circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "The game: 30.",
              MenuLabel = "Ice bolt, 2nd-3rd circle" },
            { Key = "IceBoltStep4", Kind = "number", Default = 40, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt from the 4th circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "The game: 40.",
              MenuLabel = "Ice bolt, 4th-5th circle" },
            { Key = "IceBoltStep6", Kind = "number", Default = 50, Min = 0, Max = 2000, Step = 1, Decimals = 0,
              Tiers = "default",
              Label = "Ice bolt in the 6th circle", Unit = "damage", Needs = "IceBoltSteps",
              Comment = "The game: 50.",
              MenuLabel = "Ice bolt, 6th circle" },
        },
    },
    {
        Title = "Magic: learning the circles",
        Order = 54,
        Hint = "What a teacher takes, in learning points.",
        Items = {
            { Key = "CircleCosts", Kind = "bool", Default = false,
              Tiers = { false, false, true, true, true },
              Label = "Own prices for the magic circles", Needs = "Enabled",
              Comment = "Off: the game's prices." },
            { Key = "CircleCostBasics", Kind = "number", Default = 5, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 5, 5, 4, 3, 0 },
              Label = "The basics of magic (before the 1st circle)", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 5.",
              MenuLabel = "Basics of magic (learning points)" },
            { Key = "CircleCost1", Kind = "number", Default = 10, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 10, 10, 8, 5, 0 },
              Label = "The 1st circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 10." },
            { Key = "CircleCost2", Kind = "number", Default = 15, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 15, 15, 12, 8, 0 },
              Label = "The 2nd circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 15." },
            { Key = "CircleCost3", Kind = "number", Default = 20, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 20, 20, 16, 10, 0 },
              Label = "The 3rd circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 20." },
            { Key = "CircleCost4", Kind = "number", Default = 25, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 25, 25, 20, 13, 0 },
              Label = "The 4th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 25." },
            { Key = "CircleCost5", Kind = "number", Default = 30, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 30, 30, 24, 15, 0 },
              Label = "The 5th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 30." },
            { Key = "CircleCost6", Kind = "number", Default = 40, Min = 0, Max = 200, Step = 1, Decimals = 0,
              Tiers = { 40, 40, 32, 20, 0 },
              Label = "The 6th circle", Unit = "learning points", Needs = "CircleCosts",
              Comment = "The game: 40." },
        },
    },
    {
        Title = "Magic: on screen, log",
        Order = 58,
        Items = {
            { Key = "ShowMessage", Kind = "bool", Default = true,
              Label = "Note when changes reached the game", Needs = "Enabled" },
            { Key = "LogChanges", Kind = "bool", Default = false,
              Label = "Log every value changed", Needs = "Enabled" },
            { Key = "Status", Kind = "action", Label = "Write the changes to the log",
              Comment = "The module's state and every changed value." },
        },
    },
    {
        Title = "Advanced",
        Order = 59,
        Items = {
            -- not shown in the app or the menu, not in the shipped file; can be added to config.lua by hand
            -- how many of the game's data objects are searched for per look (each search costs a few milliseconds, once per run)
            { Key = "SearchesPerLook", Kind = "number", Default = 4, Min = 1, Max = 32, Decimals = 0, Hidden = true },
            -- every so many seconds the changed values are looked at again (0 = only after a map change)
            { Key = "CheckSeconds", Kind = "number", Default = 60, Min = 0, Max = 3600, Decimals = 0, Hidden = true },
            -- how often the module looks whether there is something to do (read once, when the game starts)
            { Key = "LookMilliseconds", Kind = "number", Default = 250, Min = 50, Max = 5000, Decimals = 0, Hidden = true },
        },
    },
}

return Schema
